backend:
  name: git-gateway
  branch: main

local_backend: true

media_folder: "images/uploads"
public_folder: "/images/uploads"

collections:
  - name: "blog"
    label: "Blog Posts"
    folder: "_posts"
    create: true
    slug: "{{year}}-{{month}}-{{day}}-{{slug}}"
    fields:
      - {label: "Layout", name: "layout", widget: "hidden", default: "blog"}
      - {label: "Title", name: "title", widget: "string"}
      - {label: "Publish Date", name: "date", widget: "datetime"}
      - {label: "Featured Image", name: "thumbnail", widget: "image"}
      - {label: "Category", name: "category", widget: "select", options: ["Sustainability", "Climate Action", "Community", "Clean Energy", "Research"]}
      - {label: "Excerpt", name: "excerpt", widget: "text"}
      - {label: "Body", name: "body", widget: "markdown"}
      - {label: "Author", name: "author", widget: "string"}
      - {label: "Tags", name: "tags", widget: "list", default: []}
      - {label: "Featured", name: "featured", widget: "boolean", default: false}

  - name: "pages"
    label: "Pages"
    files:
      - file: "index.html"
        label: "Home Page"
        name: "home"
        fields:
          - {label: "Hero Title", name: "hero-title", widget: "string"}
          - {label: "Hero Subtitle", name: "hero-subtitle", widget: "string"}
          - {label: "Hero Description", name: "hero-description", widget: "text"}
          - {label: "About Section", name: "about-content", widget: "markdown"}
          - {label: "Impact Areas", name: "impact-content", widget: "markdown"}

  - name: "media"
    label: "Media & Downloads"
    folder: "cms-content"
    create: true
    fields:
      - {label: "Title", name: "title", widget: "string"}
      - {label: "Description", name: "description", widget: "text"}
      - {label: "Category", name: "category", widget: "select", options: ["documents", "videos", "images"]}
      - {label: "File Type", name: "fileType", widget: "string"}
      - {label: "File Size", name: "fileSize", widget: "string"}
      - {label: "File URL", name: "fileUrl", widget: "string"}
      - {label: "Thumbnail", name: "thumbnail", widget: "image"}
      - {label: "Date", name: "date", widget: "date"}

  - name: "jobs"
    label: "Job Openings"
    folder: "cms-content"
    create: true
    fields:
      - {label: "Title", name: "title", widget: "string"}
      - {label: "Category", name: "category", widget: "select", options: ["full-time", "part-time", "contract", "internship", "volunteer"]}
      - {label: "Description", name: "description", widget: "markdown"}
      - {label: "Location", name: "location", widget: "string"}
      - {label: "Salary", name: "salary", widget: "string"}
      - {label: "Experience", name: "experience", widget: "select", options: ["entry", "mid", "senior"]}
      - {label: "Education", name: "education", widget: "text"}
      - {label: "Responsibilities", name: "responsibilities", widget: "list"}
      - {label: "Skills", name: "skills", widget: "list"}
      - {label: "Deadline", name: "deadline", widget: "date"}
      - {label: "Contact Email", name: "contactEmail", widget: "string"}
      - {label: "Active", name: "active", widget: "boolean", default: true}
